-- Create table for CALABARZON cities/municipalities and barangays
CREATE TABLE IF NOT EXISTS calabarzon_locations (
    id SERIAL PRIMARY KEY,
    city_municipality VARCHAR(255) NOT NULL,
    barangay VARCHAR(255) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_city_municipality ON calabarzon_locations (city_municipality);

-- Insert data for CALABARZON cities and barangays
-- Cavite
INSERT INTO calabarzon_locations (city_municipality, barangay) VALUES
('Bacoor', 'Alima'),
('Bacoor', 'Aniban'),
('Bacoor', 'Banalo'),
('Bacoor', 'Camposanto'),
('Bacoor', 'Daang Bukid'),
('Bacoor', 'Digman'),
('Bacoor', 'Habay'),
('Bacoor', 'Kaingin'),
('Bacoor', 'Ligas'),
('Bacoor', 'Mabolo'),
('Bacoor', 'Maliksi'),
('Bacoor', 'Mambog'),
('Bacoor', 'Molino'),
('Bacoor', 'Niog'),
('Bacoor', 'Poblacion'),
('Bacoor', 'Queens Row Central'),
('Bacoor', 'Queens Row East'),
('Bacoor', 'Queens Row West'),
('Bacoor', 'Real'),
('Bacoor', 'Salinas'),
('Bacoor', 'San Nicolas'),
('Bacoor', 'Sineguelasan'),
('Bacoor', 'Tabing Dagat'),
('Bacoor', 'Talaba'),
('Bacoor', 'Zapote'),
('Dasmariñas', 'Burol Main'),
('Dasmariñas', 'Burol'),
('Dasmariñas', 'Datu Esmael'),
('Dasmariñas', 'Emmanuel Bergado I'),
('Dasmariñas', 'Emmanuel Bergado II'),
('Dasmariñas', 'Fatima I'),
('Dasmariñas', 'Fatima II'),
('Dasmariñas', 'Fatima III'),
('Dasmariñas', 'Hulo'),
('Dasmariñas', 'Langkaan I'),
('Dasmariñas', 'Langkaan II'),
('Dasmariñas', 'Luzviminda I'),
('Dasmariñas', 'Luzviminda II'),
('Dasmariñas', 'Paliparan I'),
('Dasmariñas', 'Paliparan II'),
('Dasmariñas', 'Paliparan III'),
('Dasmariñas', 'Sabang'),
('Dasmariñas', 'Saint Peter I'),
('Dasmariñas', 'Saint Peter II'),
('Dasmariñas', 'Salawag'),
('Dasmariñas', 'Salitran I'),
('Dasmariñas', 'Salitran II'),
('Dasmariñas', 'Salitran III'),
('Dasmariñas', 'San Agustin I'),
('Dasmariñas', 'San Agustin II'),
('Dasmariñas', 'San Agustin III'),
('Dasmariñas', 'San Andres I'),
('Dasmariñas', 'San Andres II'),
('Dasmariñas', 'San Antonio de Padua I'),
('Dasmariñas', 'San Antonio de Padua II'),
('Dasmariñas', 'San Dionisio'),
('Dasmariñas', 'San Esteban'),
('Dasmariñas', 'San Francisco I'),
('Dasmariñas', 'San Francisco II'),
('Dasmariñas', 'San Isidro I'),
('Dasmariñas', 'San Isidro II'),
('Dasmariñas', 'San Jose'),
('Dasmariñas', 'San Lorenzo Ruiz I'),
('Dasmariñas', 'San Lorenzo Ruiz II'),
('Dasmariñas', 'San Miguel I'),
('Dasmariñas', 'San Miguel II'),
('Dasmariñas', 'San Nicolas I'),
('Dasmariñas', 'San Nicolas II'),
('Dasmariñas', 'San Roque'),
('Dasmariñas', 'San Simon'),
('Dasmariñas', 'Santa Cristina I'),
('Dasmariñas', 'Santa Cristina II'),
('Dasmariñas', 'Santa Cruz I'),
('Dasmariñas', 'Santa Cruz II'),
('Dasmariñas', 'Santa Fe'),
('Dasmariñas', 'Santa Lucia'),
('Dasmariñas', 'Santa Maria'),
('Dasmariñas', 'Santo Cristo'),
('Dasmariñas', 'Santo Niño I'),
('Dasmariñas', 'Santo Niño II'),
('Dasmariñas', 'Victoria Reyes'),
('General Trias', 'Alingaro'),
('General Trias', 'Arnaldo Poblacion'),
('General Trias', 'Bacao'),
('General Trias', 'Bagumbayan'),
('General Trias', 'Biclatan'),
('General Trias', 'Buenavista I'),
('General Trias', 'Buenavista II'),
('General Trias', 'Buenavista III'),
('General Trias', 'Corregidor'),
('General Trias', 'Dulong Bayan'),
('General Trias', 'Gov. Ferrer Poblacion'),
('General Trias', 'Javalera'),
('General Trias', 'Manggahan'),
('General Trias', 'Navarro'),
('General Trias', 'Ninety Sixth Poblacion'),
('General Trias', 'Panungyanan'),
('General Trias', 'Pasong Camachile I'),
('General Trias', 'Pasong Camachile II'),
('General Trias', 'Pasong Kawayan I'),
('General Trias', 'Pasong Kawayan II'),
('General Trias', 'Pinagtipunan'),
('General Trias', 'Prinza Poblacion'),
('General Trias', 'Sampalucan Poblacion'),
('General Trias', 'San Francisco'),
('General Trias', 'San Gabriel Poblacion'),
('General Trias', 'San Juan I'),
('General Trias', 'San Juan II'),
('General Trias', 'Santa Clara'),
('General Trias', 'Santiago'),
('General Trias', 'Tapia'),
('General Trias', 'Tejero'),
('General Trias', 'Vibora Poblacion'),
('Imus', 'Alapan I-A'),
('Imus', 'Alapan I-B'),
('Imus', 'Alapan I-C'),
('Imus', 'Alapan II-A'),
('Imus', 'Alapan II-B'),
('Imus', 'Anabu I-A'),
('Imus', 'Anabu I-B'),
('Imus', 'Anabu I-C'),
('Imus', 'Anabu I-D'),
('Imus', 'Anabu I-E'),
('Imus', 'Anabu I-F'),
('Imus', 'Anabu I-G'),
('Imus', 'Anabu II-A'),
('Imus', 'Anabu II-B'),
('Imus', 'Anabu II-C'),
('Imus', 'Anabu II-D'),
('Imus', 'Anabu II-E'),
('Imus', 'Anabu II-F'),
('Imus', 'Anabu II-G'),
('Imus', 'Bacolod'),
('Imus', 'Bagong Silang'),
('Imus', 'Bayan Luma I'),
('Imus', 'Bayan Luma II'),
('Imus', 'Bayan Luma III'),
('Imus', 'Bayan Luma IV'),
('Imus', 'Bayan Luma V'),
('Imus', 'Bayan Luma VI'),
('Imus', 'Bayan Luma VII'),
('Imus', 'Bayan Luma VIII'),
('Imus', 'Bayan Luma IX'),
('Imus', 'Buhay na Tubig'),
('Imus', 'Carsadang Bago I'),
('Imus', 'Carsadang Bago II'),
('Imus', 'Magdalo'),
('Imus', 'Maharlika'),
('Imus', 'Maimpis'),
('Imus', 'Malagasang I-A'),
('Imus', 'Malagasang I-B'),
('Imus', 'Malagasang I-C'),
('Imus', 'Malagasang I-D'),
('Imus', 'Malagasang I-E'),
('Imus', 'Malagasang I-F'),
('Imus', 'Malagasang I-G'),
('Imus', 'Malagasang II-A'),
('Imus', 'Malagasang II-B'),
('Imus', 'Malagasang II-C'),
('Imus', 'Malagasang II-D'),
('Imus', 'Malagasang II-E'),
('Imus', 'Malagasang II-F'),
('Imus', 'Malagasang II-G'),
('Imus', 'Mariano Espeleta I'),
('Imus', 'Mariano Espeleta II'),
('Imus', 'Mariano Espeleta III'),
('Imus', 'Medicion I-A'),
('Imus', 'Medicion I-B'),
('Imus', 'Medicion I-C'),
('Imus', 'Medicion I-D'),
('Imus', 'Medicion I-E'),
('Imus', 'Medicion I-F'),
('Imus', 'Medicion I-G'),
('Imus', 'Medicion II-A'),
('Imus', 'Medicion II-B'),
('Imus', 'Medicion II-C'),
('Imus', 'Medicion II-D'),
('Imus', 'Medicion II-E'),
('Imus', 'Medicion II-F'),
('Imus', 'Medicion II-G'),
('Imus', 'Pajo'),
('Imus', 'Palico I'),
('Imus', 'Palico II'),
('Imus', 'Palico III'),
('Imus', 'Palico IV'),
('Imus', 'Pasong Buaya I'),
('Imus', 'Pasong Buaya II'),
('Imus', 'Pinagtipunan'),
('Imus', 'Poblacion I-A'),
('Imus', 'Poblacion I-B'),
('Imus', 'Poblacion I-C'),
('Imus', 'Poblacion II-A'),
('Imus', 'Poblacion II-B'),
('Imus', 'Poblacion II-C'),
('Imus', 'Poblacion III-A'),
('Imus', 'Poblacion III-B'),
('Imus', 'Poblacion III-C'),
('Imus', 'Poblacion IV-A'),
('Imus', 'Poblacion IV-B'),
('Imus', 'Poblacion IV-C'),
('Imus', 'Poblacion IV-D'),
('Imus', 'Tanzang Luma I'),
('Imus', 'Tanzang Luma II'),
('Imus', 'Tanzang Luma III'),
('Imus', 'Tanzang Luma IV'),
('Imus', 'Tanzang Luma V'),
('Imus', 'Tanzang Luma VI'),
('Imus', 'Toclong I-A'),
('Imus', 'Toclong I-B'),
('Imus', 'Toclong I-C'),
('Imus', 'Toclong II-A'),
('Imus', 'Toclong II-B'),
('Imus', 'Toclong II-C'),
('Imus', 'Tugasan'),
('Trece Martires', 'Aguado'),
('Trece Martires', 'Cabezas'),
('Trece Martires', 'Cabuco'),
('Trece Martires', 'Conchu (Lagundian)'),
('Trece Martires', 'De Ocampo'),
('Trece Martires', 'Gregorio (Aliang)'),
('Trece Martires', 'Inocencio (Sanggulong)'),
('Trece Martires', 'Lallana (Balsahan)'),
('Trece Martires', 'Lapidario (Bayog)'),
('Trece Martires', 'Luciano (Bitangan)'),
('Trece Martires', 'Osorio'),
('Trece Martires', 'Perez (Lucban)'),
('Trece Martires', 'San Agustin (Poblacion)'),
('Trece Martires', 'San Antonio'),
('Trece Martires', 'San Francisco (Poblacion)'),
('Trece Martires', 'San Nicolas (Poblacion)'),
('Trece Martires', 'Santiago (Poblacion)'),
('Trece Martires', 'Santa Clara (Poblacion)'),
('Trece Martires', 'Santa Cruz (Poblacion)'),
('Trece Martires', 'Santa Maria (Poblacion)'),
('Trece Martires', 'Santo Niño (Poblacion)'),
-- Laguna
('Santa Rosa', 'Aplaya'),
('Santa Rosa', 'Balibago'),
('Santa Rosa', 'Caingin'),
('Santa Rosa', 'Dila'),
('Santa Rosa', 'Dita'),
('Santa Rosa', 'Don Jose'),
('Santa Rosa', 'Ibaba'),
('Santa Rosa', 'Kanluran'),
('Santa Rosa', 'Labas'),
('Santa Rosa', 'Malitlit'),
('Santa Rosa', 'Malusak'),
('Santa Rosa', 'Market Area'),
('Santa Rosa', 'Pooc'),
('Santa Rosa', 'Pulong Santa Cruz'),
('Santa Rosa', 'Santa Domingo'),
('Santa Rosa', 'Sinalhan'),
('Santa Rosa', 'Tagapo'),
('Biñan', 'Biñan'),
('Biñan', 'Canlalay'),
('Biñan', 'Casile'),
('Biñan', 'Diezmo'),
('Biñan', 'Gulod'),
('Biñan', 'Mabini'),
('Biñan', 'Malaban'),
('Biñan', 'Malamig'),
('Biñan', 'Mampalasan'),
('Biñan', 'Platero'),
('Biñan', 'Poblacion'),
('Biñan', 'San Antonio'),
('Biñan', 'San Francisco'),
('Biñan', 'San Jose'),
('Biñan', 'San Vicente'),
('Biñan', 'San Tomas'),
('Biñan', 'Sorosoro Ibaba'),
('Biñan', 'Sorosoro Ilaya'),
('Biñan', 'Sorosoro Karsada'),
('Biñan', 'Timbao'),
('Biñan', 'Tubigan'),
('Biñan', 'Zapote'),
('Cabuyao', 'Baclaran'),
('Cabuyao', 'Banay-Banay'),
('Cabuyao', 'Banlic'),
('Cabuyao', 'Bigaa'),
('Cabuyao', 'Butong'),
('Cabuyao', 'Casile'),
('Cabuyao', 'Diezmo'),
('Cabuyao', 'Gulod'),
('Cabuyao', 'Mamatid'),
('Cabuyao', 'Marinig'),
('Cabuyao', 'Niugan'),
('Cabuyao', 'Pittland'),
('Cabuyao', 'Poblacion Uno'),
('Cabuyao', 'Poblacion Dos'),
('Cabuyao', 'Poblacion Tres'),
('Cabuyao', 'Pulo'),
('Cabuyao', 'Sala'),
('Cabuyao', 'San Isidro'),
('Cabuyao', 'Sinilaban'),
('Cabuyao', 'Tamnag'),
('Calamba', 'Bagong Kalsada'),
('Calamba', 'Bañadero'),
('Calamba', 'Barandal'),
('Calamba', 'Batino'),
('Calamba', 'Bubuyan'),
('Calamba', 'Bucal'),
('Calamba', 'Bunggo'),
('Calamba', 'Burol'),
('Calamba', 'Camaligan'),
('Calamba', 'Canlubang'),
('Calamba', 'Halang'),
('Calamba', 'Hornalan'),
('Calamba', 'Kay-Anlog'),
('Calamba', 'La Mesa'),
('Calamba', 'Laguerta'),
('Calamba', 'Lawigue'),
('Calamba', 'Mabato'),
('Calamba', 'Majada'),
('Calamba', 'Makiling'),
('Calamba', 'Mapagong'),
('Calamba', 'Masili'),
('Calamba', 'Maunong'),
('Calamba', 'Mayapa'),
('Calamba', 'Milagrosa'),
('Calamba', 'Paciano Rizal'),
('Calamba', 'Palingon'),
('Calamba', 'Palo-Alto'),
('Calamba', 'Pansol'),
('Calamba', 'Parian'),
('Calamba', 'Prinza'),
('Calamba', 'Punta'),
('Calamba', 'Puting Lupa'),
('Calamba', 'Real'),
('Calamba', 'Saimsim'),
('Calamba', 'Sampiruhan'),
('Calamba', 'San Cristobal'),
('Calamba', 'San Jose'),
('Calamba', 'San Juan'),
('Calamba', 'San Pablo Norte'),
('Calamba', 'San Pablo Sur'),
('Calamba', 'Sirang Lupa'),
('Calamba', 'Sucol'),
('Calamba', 'Turbina'),
('Calamba', 'Ulango'),
('Calamba', 'Uwisan'),
('San Pablo', 'Atisan'),
('San Pablo', 'Bagong Bayan'),
('San Pablo', 'Balibago'),
('San Pablo', 'Del Remedio'),
('San Pablo', 'Dolores'),
('San Pablo', 'San Antonio 1'),
('San Pablo', 'San Antonio 2'),
('San Pablo', 'San Bartolome'),
('San Pablo', 'San Buenaventura'),
('San Pablo', 'San Crispin'),
('San Pablo', 'San Cristobal'),
('San Pablo', 'San Diego'),
('San Pablo', 'San Francisco'),
('San Pablo', 'San Gabriel'),
('San Pablo', 'San Gregorio'),
('San Pablo', 'San Ignacio'),
('San Pablo', 'San Isidro'),
('San Pablo', 'San Joaquin'),
('San Pablo', 'San Jose'),
('San Pablo', 'San Juan'),
('San Pablo', 'San Lorenzo'),
('San Pablo', 'San Lucas 1'),
('San Pablo', 'San Lucas 2'),
('San Pablo', 'San Marcos'),
('San Pablo', 'San Mateo'),
('San Pablo', 'San Miguel'),
('San Pablo', 'San Nicolas'),
('San Pablo', 'San Pedro'),
('San Pablo', 'San Rafael'),
('San Pablo', 'San Roque'),
('San Pablo', 'Santa Ana'),
('San Pablo', 'Santa Catalina'),
('San Pablo', 'Santa Cruz'),
('San Pablo', 'Santa Elena'),
('San Pablo', 'Santa Maria'),
('San Pablo', 'Santa Monica'),
('San Pablo', 'Santa Veronica'),
('San Pablo', 'Santiago I'),
('San Pablo', 'Santiago II'),
('San Pablo', 'Santisimo Rosario'),
('San Pablo', 'Santo Angel'),
('San Pablo', 'Santo Niño'),
('San Pablo', 'Soledad'),
('Santa Cruz', 'Alipit'),
('Santa Cruz', 'Bagumbayan'),
('Santa Cruz', 'Calios'),
('Santa Cruz', 'Duhat'),
('Santa Cruz', 'Gatid'),
('Santa Cruz', 'Jasaan'),
('Santa Cruz', 'Labuin'),
('Santa Cruz', 'Malinao'),
('Santa Cruz', 'Oogong'),
('Santa Cruz', 'Pagsawitan'),
('Santa Cruz', 'Palasan'),
('Santa Cruz', 'Patimbao'),
('Santa Cruz', 'Poblacion I'),
('Santa Cruz', 'Poblacion II'),
('Santa Cruz', 'Poblacion III'),
('Santa Cruz', 'Poblacion IV'),
('Santa Cruz', 'Poblacion V'),
('Santa Cruz', 'San Jose'),
('Santa Cruz', 'San Juan'),
('Santa Cruz', 'San Pablo Norte'),
('Santa Cruz', 'San Pablo Sur'),
('Santa Cruz', 'Santisimo Rosario'),
('Santa Cruz', 'Santo Angel Central'),
('Santa Cruz', 'Santo Angel Norte'),
('Santa Cruz', 'Santo Angel Sur'),
-- Batangas
('Tanauan', 'Ambulong'),
('Tanauan', 'Bagbag'),
('Tanauan', 'Bagumbayan'),
('Tanauan', 'Balele'),
('Tanauan', 'Banadero'),
('Tanauan', 'Banjo East'),
('Tanauan', 'Banjo Laurel'),
('Tanauan', 'Batangas East'),
('Tanauan', 'Batangas West'),
('Tanauan', 'Bolbok'),
('Tanauan', 'Bugtong na Pulo'),
('Tanauan', 'Darasa'),
('Tanauan', 'Gonzales'),
('Tanauan', 'Janopol Occidental'),
('Tanauan', 'Janopol Oriental'),
('Tanauan', 'Laurel'),
('Tanauan', 'Luyos'),
('Tanauan', 'Mabini'),
('Tanauan', 'Malaking Pulo'),
('Tanauan', 'Maria Paz'),
('Tanauan', 'Maugat East'),
('Tanauan', 'Maugat West'),
('Tanauan', 'Montaña'),
('Tanauan', 'Natatas'),
('Tanauan', 'Pagaspas'),
('Tanauan', 'Pantalan'),
('Tanauan', 'Poblacion Barangay 1'),
('Tanauan', 'Poblacion Barangay 2'),
('Tanauan', 'Poblacion Barangay 3'),
('Tanauan', 'Poblacion Barangay 4'),
('Tanauan', 'Poblacion Barangay 5'),
('Tanauan', 'Poblacion Barangay 6'),
('Tanauan', 'Poblacion Barangay 7'),
('Tanauan', 'Poblacion Barangay 8'),
('Tanauan', 'Sambat'),
('Tanauan', 'San Jose'),
('Tanauan', 'San Miguel'),
('Tanauan', 'Santa Clara'),
('Tanauan', 'Santiago'),
('Tanauan', 'Talaga'),
('Tanauan', 'Tinurik'),
('Tanauan', 'Trapiche'),
('Tanauan', 'Ulango'),
('Tanauan', 'Wawa'),
('Batangas City', 'Alangilan'),
('Batangas City', 'Balagtas'),
('Batangas City', 'Balete'),
('Batangas City', 'Banaba Center'),
('Batangas City', 'Banaba East'),
('Batangas City', 'Banaba West'),
('Batangas City', 'Banaba South'),
('Batangas City', 'Banaba North'),
('Batangas City', 'Bilogo'),
('Batangas City', 'Bolbok'),
('Batangas City', 'Bukal'),
('Batangas City', 'Calicanto'),
('Batangas City', 'Concepcion'),
('Batangas City', 'Cuta'),
('Batangas City', 'Dalig'),
('Batangas City', 'Dela Paz'),
('Batangas City', 'Dela Paz Pulot Aplaya'),
('Batangas City', 'Dela Paz Pulot Itaas'),
('Batangas City', 'Domoclay'),
('Batangas City', 'Dumantay'),
('Batangas City', 'Gulod Itaas'),
('Batangas City', 'Gulod Labak'),
('Batangas City', 'Haligue Kanluran'),
('Batangas City', 'Haligue Silangan'),
('Batangas City', 'Ilijan'),
('Batangas City', 'Kumintang Ibaba'),
('Batangas City', 'Kumintang Ilaya'),
('Batangas City', 'Libjo'),
('Batangas City', 'Liponpon'),
('Batangas City', 'Mabini'),
('Batangas City', 'Magdalena'),
('Batangas City', 'Malalim'),
('Batangas City', 'Malibayo'),
('Batangas City', 'Malitam'),
('Batangas City', 'Maruclap'),
('Batangas City', 'Paharang Kanluran'),
('Batangas City', 'Paharang Silangan'),
('Batangas City', 'Pallocan Kanluran'),
('Batangas City', 'Pallocan Silangan'),
('Batangas City', 'Pinamucan Ibaba'),
('Batangas City', 'Pinamucan Proper'),
('Batangas City', 'Sampaga'),
('Batangas City', 'San Agustin'),
('Batangas City', 'San Andres'),
('Batangas City', 'San Antonio'),
('Batangas City', 'San Isidro'),
('Batangas City', 'San Jose Sico'),
('Batangas City', 'San Miguel'),
('Batangas City', 'San Pablo'),
('Batangas City', 'San Pedro'),
('Batangas City', 'San Roque'),
('Batangas City', 'San Teodoro'),
('Batangas City', 'San Vicente'),
('Batangas City', 'Santa Clara'),
('Batangas City', 'Santa Rita Aplaya'),
('Batangas City', 'Santa Rita Karsada'),
('Batangas City', 'Santo Domingo'),
('Batangas City', 'Santo Niño'),
('Batangas City', 'Santo Tomas'),
('Batangas City', 'Simlong'),
('Batangas City', 'Sirang Lupa'),
('Batangas City', 'Sorosoro Ibaba'),
('Batangas City', 'Sorosoro Ilaya'),
('Batangas City', 'Sorosoro Karsada'),
('Batangas City', 'Tabangao Aplaya'),
('Batangas City', 'Tabangao Ambulong'),
('Batangas City', 'Tabangao Dao'),
('Batangas City', 'Talumpok Kanluran'),
('Batangas City', 'Talumpok Silangan'),
('Batangas City', 'Tinga Itaas'),
('Batangas City', 'Tinga Labak'),
('Batangas City', 'Tingga Labak'),
('Batangas City', 'Tulo'),
('Batangas City', 'Wawa'),
('Lipa', 'Adya'),
('Lipa', 'Anilao'),
('Lipa', 'Anilao-Labac'),
('Lipa', 'Antipolo del Norte'),
('Lipa', 'Antipolo del Sur'),
('Lipa', 'Bagong Pook'),
('Lipa', 'Balintawak'),
('Lipa', 'Banaybanay'),
('Lipa', 'Bolbok'),
('Lipa', 'Bugtong na Pulo'),
('Lipa', 'Bulacnin'),
('Lipa', 'Bulaklakan'),
('Lipa', 'Calamias'),
('Lipa', 'Cumba'),
('Lipa', 'Dagatan'),
('Lipa', 'Halang'),
('Lipa', 'Inosloban'),
('Lipa', 'Latag'),
('Lipa', 'Lumbang'),
('Lipa', 'Mabini'),
('Lipa', 'Malagonlong'),
('Lipa', 'Malitlit'),
('Lipa', 'Marauoy'),
('Lipa', 'Mataas na Lupa'),
('Lipa', 'Munting Pulo'),
('Lipa', 'Pag-asa'),
('Lipa', 'Pangao'),
('Lipa', 'Pinagkawitan'),
('Lipa', 'Pinagtongulan'),
('Lipa', 'Plaridel'),
('Lipa', 'Poblacion Barangay 1'),
('Lipa', 'Poblacion Barangay 2'),
('Lipa', 'Poblacion Barangay 3'),
('Lipa', 'Poblacion Barangay 4'),
('Lipa', 'Poblacion Barangay 5'),
('Lipa', 'Poblacion Barangay 6'),
('Lipa', 'Poblacion Barangay 7'),
('Lipa', 'Poblacion Barangay 8'),
('Lipa', 'Poblacion Barangay 9'),
('Lipa', 'Poblacion Barangay 10'),
('Lipa', 'Poblacion Barangay 11'),
('Lipa', 'Poblacion Barangay 12'),
('Lipa', 'Poblacion Barangay 13'),
('Lipa', 'Poblacion Barangay 14'),
('Lipa', 'Poblacion Barangay 15'),
('Lipa', 'Poblacion Barangay 16'),
('Lipa', 'Poblacion Barangay 17'),
('Lipa', 'Poblacion Barangay 18'),
('Lipa', 'Poblacion Barangay 19'),
('Lipa', 'Poblacion Barangay 20'),
('Lipa', 'Poblacion Barangay 21'),
('Lipa', 'Poblacion Barangay 22'),
('Lipa', 'Poblacion Barangay 23'),
('Lipa', 'Poblacion Barangay 24'),
('Lipa', 'Poblacion Barangay 25'),
('Lipa', 'Poblacion Barangay 26'),
('Lipa', 'Poblacion Barangay 27'),
('Lipa', 'Poblacion Barangay 28'),
('Lipa', 'Poblacion Barangay 29'),
('Lipa', 'Poblacion Barangay 30'),
('Lipa', 'Poblacion Barangay 31'),
('Lipa', 'Poblacion Barangay 32'),
('Lipa', 'Poblacion Barangay 33'),
('Lipa', 'Poblacion Barangay 34'),
('Lipa', 'Poblacion Barangay 35'),
('Lipa', 'Poblacion Barangay 36'),
('Lipa', 'Poblacion Barangay 37'),
('Lipa', 'Poblacion Barangay 38'),
('Lipa', 'Poblacion Barangay 39'),
('Lipa', 'Poblacion Barangay 40'),
('Lipa', 'Poblacion Barangay 41'),
('Lipa', 'Poblacion Barangay 42'),
('Lipa', 'Poblacion Barangay 43'),
('Lipa', 'Poblacion Barangay 44'),
('Lipa', 'Poblacion Barangay 45'),
('Lipa', 'Poblacion Barangay 46'),
('Lipa', 'Poblacion Barangay 47'),
('Lipa', 'Poblacion Barangay 48'),
('Lipa', 'Poblacion Barangay 49'),
('Lipa', 'Poblacion Barangay 50'),
('Lipa', 'Poblacion Barangay 51'),
('Lipa', 'Poblacion Barangay 52'),
('Lipa', 'Poblacion Barangay 53'),
('Lipa', 'Poblacion Barangay 54'),
('Lipa', 'Poblacion Barangay 55'),
('Lipa', 'Poblacion Barangay 56'),
('Lipa', 'Poblacion Barangay 57'),
('Lipa', 'Poblacion Barangay 58'),
('Lipa', 'Poblacion Barangay 59'),
('Lipa', 'Poblacion Barangay 60'),
('Lipa', 'Poblacion Barangay 61'),
('Lipa', 'Poblacion Barangay 62'),
('Lipa', 'Poblacion Barangay 63'),
('Lipa', 'Poblacion Barangay 64'),
('Lipa', 'Poblacion Barangay 65'),
('Lipa', 'Poblacion Barangay 66'),
('Lipa', 'Poblacion Barangay 67'),
('Lipa', 'Poblacion Barangay 68'),
('Lipa', 'Poblacion Barangay 69'),
('Lipa', 'Poblacion Barangay 70'),
('Lipa', 'Poblacion Barangay 71'),
('Lipa', 'Poblacion Barangay 72'),
('Lipa', 'Poblacion Barangay 73'),
('Lipa', 'Poblacion Barangay 74'),
('Lipa', 'Poblacion Barangay 75'),
('Lipa', 'Poblacion Barangay 76'),
('Lipa', 'Poblacion Barangay 77'),
('Lipa', 'Poblacion Barangay 78'),
('Lipa', 'Poblacion Barangay 79'),
('Lipa', 'Poblacion Barangay 80'),
('Lipa', 'Poblacion Barangay 81'),
('Lipa', 'Poblacion Barangay 82'),
('Lipa', 'Poblacion Barangay 83'),
('Lipa', 'Poblacion Barangay 84'),
('Lipa', 'Poblacion Barangay 85'),
('Lipa', 'Poblacion Barangay 86'),
('Lipa', 'Poblacion Barangay 87'),
('Lipa', 'Poblacion Barangay 88'),
('Lipa', 'Poblacion Barangay 89'),
('Lipa', 'Poblacion Barangay 90'),
('Lipa', 'Poblacion Barangay 91'),
('Lipa', 'Poblacion Barangay 92'),
('Lipa', 'Poblacion Barangay 93'),
('Lipa', 'Poblacion Barangay 94'),
('Lipa', 'Poblacion Barangay 95'),
('Lipa', 'Poblacion Barangay 96'),
('Lipa', 'Poblacion Barangay 97'),
('Lipa', 'Poblacion Barangay 98'),
('Lipa', 'Poblacion Barangay 99'),
('Lipa', 'Poblacion Barangay 100'),
('Lipa', 'Poblacion Barangay 101'),
('Lipa', 'Poblacion Barangay 102'),
('Lipa', 'Poblacion Barangay 103'),
('Lipa', 'Poblacion Barangay 104'),
('Lipa', 'Poblacion Barangay 105'),
('Lipa', 'Poblacion Barangay 106'),
('Lipa', 'Poblacion Barangay 107'),
('Lipa', 'Poblacion Barangay 108'),
('Lipa', 'Poblacion Barangay 109'),
('Lipa', 'Poblacion Barangay 110'),
('Lipa', 'Poblacion Barangay 111'),
('Lipa', 'Poblacion Barangay 112'),
('Lipa', 'Poblacion Barangay 113'),
('Lipa', 'Poblacion Barangay 114'),
('Lipa', 'Poblacion Barangay 115'),
('Lipa', 'Poblacion Barangay 116'),
('Lipa', 'Poblacion Barangay 117'),
('Lipa', 'Poblacion Barangay 118'),
('Lipa', 'Poblacion Barangay 119'),
('Lipa', 'Poblacion Barangay 120'),
('Lipa', 'Poblacion Barangay 121'),
('Lipa', 'Poblacion Barangay 122'),
('Lipa', 'Poblacion Barangay 123'),
('Lipa', 'Poblacion Barangay 124'),
('Lipa', 'Poblacion Barangay 125'),
('Lipa', 'Poblacion Barangay 126'),
('Lipa', 'Poblacion Barangay 127'),
('Lipa', 'Poblacion Barangay 128'),
('Lipa', 'Poblacion Barangay 129'),
('Lipa', 'Poblacion Barangay 130'),
('Lipa', 'Poblacion Barangay 131'),
('Lipa', 'Poblacion Barangay 132'),
('Lipa', 'Poblacion Barangay 133'),
('Lipa', 'Poblacion Barangay 134'),
('Lipa', 'Poblacion Barangay 135'),
('Lipa', 'Poblacion Barangay 136'),
('Lipa', 'Poblacion Barangay 137'),
('Lipa', 'Poblacion Barangay 138'),
('Lipa', 'Poblacion Barangay 139'),
('Lipa', 'Poblacion Barangay 140'),
('Lipa', 'Poblacion Barangay 141'),
('Lipa', 'Poblacion Barangay 142'),
('Lipa', 'Poblacion Barangay 143'),
('Lipa', 'Poblacion Barangay 144'),
('Lipa', 'Poblacion Barangay 145'),
('Lipa', 'Poblacion Barangay 146'),
('Lipa', 'Poblacion Barangay 147'),
('Lipa', 'Poblacion Barangay 148'),
('Lipa', 'Poblacion Barangay 149'),
('Lipa', 'Poblacion Barangay 150'),
('Lipa', 'Poblacion Barangay 151'),
('Lipa', 'Poblacion Barangay 152'),
('Lipa', 'Poblacion Barangay 153'),
('Lipa', 'Poblacion Barangay 154'),
('Lipa', 'Poblacion Barangay 155'),
('Lipa', 'Poblacion Barangay 156'),
('Lipa', 'Poblacion Barangay 157'),
('Lipa', 'Poblacion Barangay 158'),
('Lipa', 'Poblacion Barangay 159'),
('Lipa', 'Poblacion Barangay 160'),
('Lipa', 'Poblacion Barangay 161'),
('Lipa', 'Poblacion Barangay 162'),
('Lipa', 'Poblacion Barangay 163'),
('Lipa', 'Poblacion Barangay 164'),
('Lipa', 'Poblacion Barangay 165'),
('Lipa', 'Poblacion Barangay 166'),
('Lipa', 'Poblacion Barangay 167'),
('Lipa', 'Poblacion Barangay 168'),
('Lipa', 'Poblacion Barangay 169'),
('Lipa', 'Poblacion Barangay 170'),
('Lipa', 'Poblacion Barangay 171'),
('Lipa', 'Poblacion Barangay 172'),
('Lipa', 'Poblacion Barangay 173'),
('Binangonan', 'Kamalig'),
('Binangonan', 'Kamalig'),
('Binangonan', 'Libid'),
('Binangonan', 'Libis'),
('Binangonan', 'Lunsad'),
('Binangonan', 'Mambog'),
('Binangonan', 'Pantok'),
('Binangonan', 'Pila-Pila'),
('Binangonan', 'Pipindan'),
('Binangonan', 'Rayap'),
('Binangonan', 'Sapang'),
('Binangonan', 'Tagpos'),
('Binangonan', 'Tatala'),
('Binangonan', 'Tayuman'),
('Binangonan', 'Tocal'),
('Binangonan', 'Tuna'),
('Binangonan', 'Wawa'),

('Antipolo', 'Bagong Nayon'),
('Antipolo', 'Beverly Hills'),
('Antipolo', 'Cupang'),
('Antipolo', 'Dalig'),
('Antipolo', 'Dela Paz'),
('Antipolo', 'Inarawan'),
('Antipolo', 'Mambugan'),
('Antipolo', 'Mayamot'),
('Antipolo', 'Muntingdilao'),
('Antipolo', 'San Isidro'),
('Antipolo', 'San Jose'),
('Antipolo', 'San Juan'),
('Antipolo', 'San Luis'),
('Antipolo', 'San Roque'),
('Antipolo', 'Santa Cruz'),
('Antipolo', 'Santa Cruz (Upper)'),
('Antipolo', 'Santa Cruz (Lower)'),
('Antipolo', 'Santa Maria'),
('Antipolo', 'Santo Niño'),
('Antipolo', 'Santo Rosario'),
('Antipolo', 'Sitio Maagay'),
('Antipolo', 'Sitio Tanza'),

('Cainta', 'San Andres'),
('Cainta', 'San Isidro'),
('Cainta', 'San Juan'),
('Cainta', 'San Roque'),
('Cainta', 'Santa Rosa'),
('Cainta', 'Santo Domingo'),

('Taytay', 'Dolores'),
('Taytay', 'Muzon'),
('Taytay', 'San Isidro'),
('Taytay', 'San Juan'),
('Taytay', 'Santa Ana'),

('Angono', 'Kalayaan'),
('Angono', 'Mahabang Parang'),
('Angono', 'Poblacion Ibaba'),
('Angono', 'Poblacion Itaas'),
('Angono', 'San Isidro'),
('Angono', 'San Pedro'),

('Cardona', 'Balibago'),
('Cardona', 'Calahan'),
('Cardona', 'Del Remedio'),
('Cardona', 'Ithan'),
('Cardona', 'Lambac'),
('Cardona', 'Looc'),
('Cardona', 'Malanggam-Calubacan'),
('Cardona', 'Patunhay'),
('Cardona', 'Poblacion'),
('Cardona', 'San Roque'),
('Cardona', 'Subay'),
('Cardona', 'Ticulio'),

('Jalajala', 'Bagumbong'),
('Jalajala', 'Bayugo'),
('Jalajala', 'Lawa'),
('Jalajala', 'Lubo'),
('Jalajala', 'Pagkalinawan'),
('Jalajala', 'Paalaman'),
('Jalajala', 'Punta'),
('Jalajala', 'Second District'),
('Jalajala', 'Special District'),
('Jalajala', 'Third District'),

('Morong', 'Bombongan'),
('Morong', 'Lagundi'),
('Morong', 'Maybancal'),
('Morong', 'San Guillermo'),
('Morong', 'San Juan'),
('Morong', 'San Pedro'),
('Morong', 'San Roque'),
('Morong', 'San Jose'),
('Morong', 'San Guillermo'),

('Pililla', 'Bagumbayan'),
('Pililla', 'Hulo'),
('Pililla', 'Imatong'),
('Pililla', 'Malaya'),
('Pililla', 'Niogan'),
('Pililla', 'Quisao'),
('Pililla', 'Takungan'),
('Pililla', 'Wawa'),

('Rodriguez (Montalban)', 'Balite'),
('Rodriguez (Montalban)', 'Burgos'),
('Rodriguez (Montalban)', 'Geronimo'),
('Rodriguez (Montalban)', 'Macabud'),
('Rodriguez (Montalban)', 'Mascap'),
('Rodriguez (Montalban)', 'Puray'),
('Rodriguez (Montalban)', 'Rosario'),
('Rodriguez (Montalban)', 'San Isidro'),
('Rodriguez (Montalban)', 'San Jose'),
('Rodriguez (Montalban)', 'San Rafael'),
('Rodriguez (Montalban)', 'San Rafael Proper'),
('Rodriguez (Montalban)', 'Silangan'),

('San Mateo', 'Ampid I'),
('San Mateo', 'Ampid II'),
('San Mateo', 'Banaba'),
('San Mateo', 'Dulong Bayan 1'),
('San Mateo', 'Dulong Bayan 2'),
('San Mateo', 'Guitnang Bayan 1'),
('San Mateo', 'Guitnang Bayan 2'),
('San Mateo', 'Malanday'),
('San Mateo', 'Maly'),
('San Mateo', 'Pintong Bukawe'),
('San Mateo', 'Santa Ana'),
('San Mateo', 'Silangan'),

('Tanay', 'Cayabu'),
('Tanay', 'Cuyambay'),
('Tanay', 'Daraitan'),
('Tanay', 'Katipunan-Bayani'),
('Tanay', 'Laiban'),
('Tanay', 'Mag-Ampon'),
('Tanay', 'Plaza Aldea'),
('Tanay', 'Sampaloc'),
('Tanay', 'San Andres'),
('Tanay', 'San Isidro'),
('Tanay', 'Santa Inez'),
('Tanay', 'Santo Niño'),
('Tanay', 'Tabing Ilog'),
('Tanay', 'Tandang Kutyo'),
('Tanay', 'Tinucan'),
('Tanay', 'Wawa'),

('Teresa', 'Bagumbayan'),
('Teresa', 'Calumpang'),
('Teresa', 'Dalig'),
('Teresa', 'May-Iba'),
('Teresa', 'Poblacion'),
('Teresa', 'Prinza'),
('Teresa', 'San Gabriel'),
('Teresa', 'San Roque'),
('Teresa', 'San Vicente');

-- ✅ CAVITE (additional municipalities)
('Amadeo', 'Banaybanay'),
('Amadeo', 'Bucal'),
('Amadeo', 'Dagatan'),
('Amadeo', 'Halang'),
('Amadeo', 'Loma'),
('Amadeo', 'Maymangga'),
('Amadeo', 'Minantok Kanluran'),
('Amadeo', 'Minantok Silangan'),
('Amadeo', 'Pangil'),
('Amadeo', 'Poblacion I'),
('Amadeo', 'Poblacion II'),
('Amadeo', 'Poblacion III'),
('Amadeo', 'Poblacion IV'),
('Amadeo', 'Salaban'),
('Amadeo', 'Talimundoc'),
('Amadeo', 'Tamacan'),

('General Mariano Alvarez', 'San Gabriel'),
('General Mariano Alvarez', 'San Jose'),
('General Mariano Alvarez', 'San Juan'),
('General Mariano Alvarez', 'San Pedro'),
('General Mariano Alvarez', 'San Rafael'),
('General Mariano Alvarez', 'San Antonio'),
('General Mariano Alvarez', 'San Andres'),

('Ternate', 'Bucana'),
('Ternate', 'Poblacion I'),
('Ternate', 'Poblacion II'),
('Ternate', 'San Jose'),
('Ternate', 'San Juan I'),
('Ternate', 'San Juan II'),
('Ternate', 'San Juan III'),
('Ternate', 'San Juan IV'),

-- ✅ LAGUNA (a few not in your earlier list)
('Liliw', 'Bagong Anyo'),
('Liliw', 'Bayate'),
('Liliw', 'Bongkol'),
('Liliw', 'Cabuyew'),
('Liliw', 'Calumpang'),
('Liliw', 'Daniw'),
('Liliw', 'Dita'),
('Liliw', 'Ibabang Palina'),
('Liliw', 'Ilayang Palina'),
('Liliw', 'Kanluran'),
('Liliw', 'Malabo-Kalantukan'),
('Liliw', 'Masikap'),
('Liliw', 'Pag-Asa'),
('Liliw', 'Oples'),
('Liliw', 'San Isidro'),
('Liliw', 'Taytay'),
('Liliw', 'Tuy-Baanan'),

('Paete', 'Bagumbayan'),
('Paete', 'Bangkusay'),
('Paete', 'Maytoong'),
('Paete', 'Ibaba del Norte'),
('Paete', 'Ilaya del Norte'),
('Paete', 'Ibaba del Sur'),
('Paete', 'Ilaya del Sur'),

-- ✅ RIZAL (additional towns)
('Baras', 'Evangelista'),
('Baras', 'Rizal'),
('Baras', 'San Jose'),
('Baras', 'San Salvador'),
('Baras', 'Pinugay'),
('Baras', 'Santiago'),
('Baras', 'San Juan'),
('Baras', 'San Miguel'),
('Baras', 'Concepcion'),

('Tanay', 'Kaytitinga'),
('Tanay', 'Tandang Kutyo'),
('Tanay', 'Tinucan'),
('Tanay', 'Sampaloc'),
('Tanay', 'Laiban'),

-- ✅ QUEZON PROVINCE
('Lucena City', 'Barangay Dalahican'),
('Lucena City', 'Barangay Ibabang Iyam'),
('Lucena City', 'Barangay Ibabang Dupay'),
('Lucena City', 'Barangay Ibabang Talim'),
('Lucena City', 'Barangay Ilayang Iyam'),
('Lucena City', 'Barangay Ilayang Dupay'),
('Lucena City', 'Barangay Gulang-Gulang'),
('Lucena City', 'Barangay Isabang'),
('Lucena City', 'Barangay Mayao Castillo'),
('Lucena City', 'Barangay Mayao Parada'),
('Lucena City', 'Barangay Mayao Crossing'),
('Lucena City', 'Barangay Ransohan'),
('Lucena City', 'Barangay 1'),
('Lucena City', 'Barangay 2'),
('Lucena City', 'Barangay 3'),
('Lucena City', 'Barangay 4'),
('Lucena City', 'Barangay 5'),
('Lucena City', 'Barangay 6'),
('Lucena City', 'Barangay 7'),
('Lucena City', 'Barangay 8'),
('Lucena City', 'Barangay 9'),
('Lucena City', 'Barangay 10'),

('Tayabas City', 'Alsam Ibaba'),
('Tayabas City', 'Alsam Ilaya'),
('Tayabas City', 'Angeles Zone I'),
('Tayabas City', 'Angeles Zone II'),
('Tayabas City', 'Angeles Zone III'),
('Tayabas City', 'Calumpang'),
('Tayabas City', 'Ipilan'),
('Tayabas City', 'Lakawan'),
('Tayabas City', 'Masin'),
('Tayabas City', 'Mate'),
('Tayabas City', 'Mayowe'),
('Tayabas City', 'Muzon'),
('Tayabas City', 'Opias'),
('Tayabas City', 'Pook'),
('Tayabas City', 'Potol'),
('Tayabas City', 'San Diego Zone I'),
('Tayabas City', 'San Diego Zone II'),
('Tayabas City', 'San Diego Zone III'),
('Tayabas City', 'San Isidro Zone I'),
('Tayabas City', 'San Isidro Zone II'),
('Tayabas City', 'San Isidro Zone III'),

('Atimonan', 'Balubad'),
('Atimonan', 'Barangay Zone I'),
('Atimonan', 'Barangay Zone II'),
('Atimonan', 'Barangay Zone III'),
('Atimonan', 'Barangay Zone IV'),
('Atimonan', 'Barangay Zone V'),
('Atimonan', 'Barangay Zone VI'),
('Atimonan', 'Habingan'),
('Atimonan', 'Inaclagan'),
('Atimonan', 'Inaclagan Ibaba'),
('Atimonan', 'Kilait'),
('Atimonan', 'Malinao Ibaba'),
('Atimonan', 'Malinao Ilaya'),
('Atimonan', 'Malusak'),
('Atimonan', 'Manggalang'),
('Atimonan', 'Pook'),
('Atimonan', 'San Isidro'),
('Atimonan', 'Tagbakin'),
('Atimonan', 'Tinandog'),

('Pagbilao', 'Barangay Daungan'),
('Pagbilao', 'Barangay Ibabang Bagumbungan'),
('Pagbilao', 'Barangay Ibabang Palsabangon'),
('Pagbilao', 'Barangay Ilayang Bagumbungan'),
('Pagbilao', 'Barangay Ilayang Palsabangon'),
('Pagbilao', 'Barangay Kanlurang Malicboy'),
('Pagbilao', 'Barangay Mapagong'),
('Pagbilao', 'Barangay Silangang Malicboy'),
('Pagbilao', 'Barangay Talipan'),
('Pagbilao', 'Barangay Tambak'),
('Pagbilao', 'Barangay Bukal'),
('Pagbilao', 'Barangay Parang'),
('Pagbilao', 'Barangay Sta. Catalina'),
('Pagbilao', 'Barangay Sta. Catalina Norte'),

('Sariaya', 'Antipolo'),
('Sariaya', 'Bignay 1'),
('Sariaya', 'Bignay 2'),
('Sariaya', 'Canda'),
('Sariaya', 'Castanas'),
('Sariaya', 'Concepcion 1'),
('Sariaya', 'Concepcion Banahaw'),
('Sariaya', 'Guisguis Talon'),
('Sariaya', 'Guisguis San Roque'),
('Sariaya', 'Manggalang 1'),
('Sariaya', 'Manggalang 2'),
('Sariaya', 'Sampaloc 1'),
('Sariaya', 'Sampaloc 2'),
('Sariaya', 'Talaan Aplaya'),
('Sariaya', 'Talaan Ilaya'),

('Lucban', 'Abang'),
('Lucban', 'Aliliw'),
('Lucban', 'Ayuti'),
('Lucban', 'Cagsiay 1'),
('Lucban', 'Cagsiay 2'),
('Lucban', 'Cagsiay 3'),
('Lucban', 'Kalyaat'),
('Lucban', 'Kulapi'),
('Lucban', 'Malupak'),
('Lucban', 'May-It'),
('Lucban', 'Palola'),
('Lucban', 'Piis'),
('Lucban', 'Samil'),
('Lucban', 'Tiawe'),
('Lucban', 'Tinagay'),

('Infanta', 'Agos-Agos'),
('Infanta', 'Amolongin'),
('Infanta', 'Anibong'),
('Infanta', 'Banti'),
('Infanta', 'Batican'),
('Infanta', 'Binonoan'),
('Infanta', 'Binulasan'),
('Infanta', 'Comon'),
('Infanta', 'Dinahican'),
('Infanta', 'Pilaway'),
('Infanta', 'Tongohin'),

('Real', 'Capalong'),
('Real', 'Kiloloron'),
('Real', 'Llavac'),
('Real', 'Maragondon'),
('Real', 'Masikap'),
('Real', 'Tignoan'),

('General Nakar', 'Anoling'),
('General Nakar', 'Baay'),
('General Nakar', 'Banglos'),
('General Nakar', 'Canaway'),
('General Nakar', 'Catablingan'),
('General Nakar', 'Minahan Norte'),
('General Nakar', 'Minahan Sur'),
('General Nakar', 'Pagsangahan'),
('General Nakar', 'Pamplona'),
('General Nakar', 'Umiray');

-- ✅ END OF CALABARZON (Region IV-A) DATA
